spring:
  data:
    mongodb:
      uri: mongodb://user:pwd@127.0.0.1:27017/goku?authSource=admin
  redis:
    repositories:
      enabled: false
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
